# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: shout_splash_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: shout_splash_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: shout_splash_prod
  pool: 5
  username: root
  password:
